/**
 * Generated from platform/contracts/schema.json by npm run contracts:generate.
 * Edit the Python contracts, then run make contracts. Do not edit this file directly.
 */

/**
 * Public contracts exchanged between Sentinel planes.
 */
export type SentinelContract = Observation | ContextWindow | DecompFrame | Symptom;
export type TelemetryScalar = string | boolean | number;
export type Identifier = string;
export type FlowRefs = Identifier[];
export type LogRefs = Identifier[];
export type SignalName = string;
export type TraceRefs = Identifier[];
export type UtcDatetime = string;
export type FiniteFloat = number;
export type HumanText = string;
export type Probability = number;
export type ContextIds = Identifier[];
export type EvidenceRefs = Identifier[];
/**
 * Deterministic evidence categories understood by the decision plane.
 */
export type SymptomKind =
  | "RESIDUAL_EXCEED"
  | "RATIO_DEFORM"
  | "LOG_BURST"
  | "EDGE_DEGRADED"
  | "SATURATION"
  | "DEPLOY_MARKER"
  | "DROP"
  | "SILENCE";

/**
 * One event-time telemetry value, containing evidence but never answer-key data.
 */
export interface Observation {
  attributes?: Attributes;
  flow_refs?: FlowRefs;
  log_refs?: LogRefs;
  observation_id: Identifier;
  service: Identifier;
  signal: SignalName;
  trace_refs?: TraceRefs;
  ts: UtcDatetime;
  unit?: string;
  value: FiniteFloat;
}
export interface Attributes {
  [k: string]: TelemetryScalar;
}
/**
 * A trusted external event and the signals whose volume it may explain.
 */
export interface ContextWindow {
  context_id: Identifier;
  event_type: Identifier;
  expected_delta: ExpectedDelta;
  name: HumanText;
  source: Identifier;
  trust_score: Probability;
  valid_from: UtcDatetime;
  valid_to: UtcDatetime;
}
export interface ExpectedDelta {
  [k: string]: FiniteFloat;
}
/**
 * Full-resolution split of observed telemetry into explained and residual parts.
 */
export interface DecompFrame {
  band_high: FiniteFloat;
  band_low: FiniteFloat;
  context_ids?: ContextIds;
  explained_base: FiniteFloat;
  explained_event: FiniteFloat;
  frame_id: Identifier;
  observation_id: Identifier;
  observed: FiniteFloat;
  residual: FiniteFloat;
  residual_score: Probability;
  service: Identifier;
  signal: SignalName;
  ts: UtcDatetime;
}
/**
 * One scored, human-legible piece of evidence about abnormal behavior.
 */
export interface Symptom {
  evidence_refs?: EvidenceRefs;
  kind: SymptomKind;
  note: HumanText;
  onset_ts: UtcDatetime;
  score: Probability;
  service: Identifier;
  signal: SignalName;
  symptom_id: Identifier;
}
