/**
 * Generated from platform/contracts/schema.json by npm run contracts:generate.
 * Edit the Python contracts, then run make contracts. Do not edit this file directly.
 */

/**
 * Public contracts exchanged between Sentinel planes.
 */
export type SentinelContract =
  | Observation
  | ContextWindow
  | DecompFrame
  | Symptom
  | SymptomEpisode
  | ChangeEvent
  | AgentAssessment
  | Verdict
  | Incident;
export type TelemetryScalar = string | boolean | number;
export type Identifier = string;
export type FlowRefs = Identifier[];
export type LogRefs = Identifier[];
export type SignalName = string;
export type TraceRefs = Identifier[];
export type UtcDatetime = string;
export type FiniteFloat = number;
export type Honesty = "REAL" | "SIMULATED";
export type HumanText = string;
export type Probability = number;
export type ContextIds = Identifier[];
export type EvidenceRefs = Identifier[];
/**
 * Deterministic evidence categories understood by the decision plane.
 */
export type SymptomKind =
  | "RESIDUAL_EXCEED"
  | "RATIO_DEFORM"
  | "LOG_BURST"
  | "EDGE_DEGRADED"
  | "SATURATION"
  | "DEPLOY_MARKER"
  | "DROP"
  | "SILENCE";
export type BreachTickCount = number;
export type EvidenceRefs1 = Identifier[];
export type Revision = number;
/**
 * Lifecycle state of an anti-flapping symptom episode.
 */
export type EpisodeStatus = "ACTIVE" | "CLOSED";
export type EvidenceRefs2 = Identifier[];
export type Honesty1 = "REAL" | "SIMULATED";
/**
 * How the system was changed by its operators, not by its callers.
 */
export type ChangeKind = "DEPLOY" | "ROLLOUT" | "FLAG" | "CONFIG";
/**
 * The independent axes a surge is judged on, one agent per axis.
 *
 * Each axis is scored from its own claimed evidence only. An attacker who
 * keeps one axis calm cannot thereby quiet another, because no agent ever
 * reads another agent's score.
 */
export type EvidenceAxis = "SECURITY" | "RELIABILITY" | "CHANGE_CONFIG" | "BUSINESS_IMPACT";
export type ContributingKinds = SymptomKind[];
export type CoveredKinds = SymptomKind[];
/**
 * Which way a measured value sits relative to its stated baseline.
 */
export type EvidenceDirection = "ABOVE_BASELINE" | "BELOW_BASELINE" | "AT_BASELINE";
export type EvidenceRefs3 = Identifier[];
export type Evidence = EvidenceItem[];
export type Services = Identifier[];
/**
 * Whether an agent had the coverage to score its axis at all.
 */
export type AgentStatus = "SCORED" | "INSUFFICIENT";
/**
 * Direction of an axis score against the agent's previous assessment.
 */
export type AgentTrend = "RISING" | "FALLING" | "STEADY" | "UNKNOWN";
export type AssessmentIds = Identifier[];
export type CorroboratingKinds = SymptomKind[];
export type Evidence1 = EvidenceItem[];
/**
 * A refinement that changes what a sane response looks like.
 *
 * ``CAPACITY_SHORTAGE`` exists so under-provisioning is answered with
 * "scale", never with "block": the traffic is real and the system is simply
 * too small for it.
 */
export type ReasonSubtype = "CAPACITY_SHORTAGE";
/**
 * What the fused evidence says is actually happening.
 */
export type VerdictClass = "EXPECTED_EVENT" | "ATTACK" | "OPERATIONAL_FAULT" | "CODE_CONFIG_FAULT" | "COMBINATION";
export type RejectedAlternatives = RejectedAlternative[];
export type Services1 = Identifier[];
/**
 * @minItems 1
 */
export type EpisodeIds = [Identifier, ...Identifier[]];
/**
 * @minItems 1
 */
export type Kinds = [SymptomKind, ...SymptomKind[]];
export type MergedIncidentIds = Identifier[];
export type Revision1 = number;
/**
 * @minItems 1
 */
export type Services2 = [Identifier, ...Identifier[]];
/**
 * How much this incident matters, in the language a responder pages on.
 */
export type IncidentSeverity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
/**
 * Where an incident is in its life, from first symptom to resolved.
 */
export type IncidentState = "OPEN" | "MITIGATING" | "MONITORING" | "RESOLVED";

/**
 * One event-time telemetry value, containing evidence but never answer-key data.
 */
export interface Observation {
  attributes?: Attributes;
  flow_refs?: FlowRefs;
  log_refs?: LogRefs;
  observation_id: Identifier;
  service: Identifier;
  signal: SignalName;
  trace_refs?: TraceRefs;
  ts: UtcDatetime;
  unit?: string;
  value: FiniteFloat;
}
export interface Attributes {
  [k: string]: TelemetryScalar;
}
/**
 * A trusted external event and the signals whose volume it may explain.
 */
export interface ContextWindow {
  context_id: Identifier;
  event_type: Identifier;
  expected_delta: ExpectedDelta;
  honesty: Honesty;
  name: HumanText;
  source: Identifier;
  trust_score: Probability;
  valid_from: UtcDatetime;
  valid_to: UtcDatetime;
}
export interface ExpectedDelta {
  [k: string]: FiniteFloat;
}
/**
 * Full-resolution split of observed telemetry into explained and residual parts.
 */
export interface DecompFrame {
  band_high: FiniteFloat;
  band_low: FiniteFloat;
  context_ids?: ContextIds;
  explained_base: FiniteFloat;
  explained_event: FiniteFloat;
  frame_id: Identifier;
  observation_id: Identifier;
  observed: FiniteFloat;
  residual: FiniteFloat;
  residual_score: Probability;
  service: Identifier;
  signal: SignalName;
  ts: UtcDatetime;
}
/**
 * One scored, human-legible piece of evidence about abnormal behavior.
 */
export interface Symptom {
  evidence_refs?: EvidenceRefs;
  kind: SymptomKind;
  note: HumanText;
  onset_ts: UtcDatetime;
  score: Probability;
  service: Identifier;
  signal: SignalName;
  symptom_id: Identifier;
}
/**
 * A hysteresis-guarded lifecycle over repeated symptoms of one key.
 *
 * An episode groups the recurring symptoms of a single ``(kind, service,
 * signal)`` into one durable incident-precursor. It opens only after a symptom
 * persists (breach persistence + a score deadband) and closes only after it
 * clears for long enough, so a momentary blip can never open one and a key can
 * never flap. Raw ``Symptom`` evidence is untouched; an episode only points at
 * it via the opening, peak and latest symptom ids.
 */
export interface SymptomEpisode {
  breach_tick_count: BreachTickCount;
  closed_ts?: UtcDatetime | null;
  confirmed_ts: UtcDatetime;
  episode_id: Identifier;
  evidence_refs?: EvidenceRefs1;
  kind: SymptomKind;
  last_breach_ts: UtcDatetime;
  latest_symptom_id: Identifier;
  opened_ts: UtcDatetime;
  opening_symptom_id: Identifier;
  peak_score: Probability;
  peak_symptom_id: Identifier;
  revision: Revision;
  service: Identifier;
  signal: SignalName;
  status: EpisodeStatus;
}
/**
 * One recorded operator change, the raw material of deploy-correlated pressure.
 *
 * A change is a fact about the system's own history, never a conclusion about
 * an incident. It carries its own honesty label because the MVP feed mixes an
 * operator-maintained ledger with changes observed from the cluster.
 */
export interface ChangeEvent {
  change_id: Identifier;
  evidence_refs?: EvidenceRefs2;
  honesty: Honesty1;
  kind: ChangeKind;
  revision?: Identifier | null;
  service: Identifier;
  source: Identifier;
  summary: HumanText;
  ts: UtcDatetime;
}
/**
 * One agent's evidence-backed verdict about one axis at one event time.
 *
 * A calm axis (``SCORED`` at ``0.0`` with no evidence) is a genuine finding:
 * the claimed detectors ran and saw nothing. An axis whose detectors produced
 * no coverage is ``INSUFFICIENT`` instead, so absence of evidence is never
 * silently reported as evidence of absence.
 */
export interface AgentAssessment {
  assessment_id: Identifier;
  axis: EvidenceAxis;
  contributing_kinds?: ContributingKinds;
  covered_kinds?: CoveredKinds;
  evidence?: Evidence;
  note: HumanText;
  score: Probability;
  services?: Services;
  status: AgentStatus;
  trend: AgentTrend;
  ts: UtcDatetime;
}
/**
 * One measured value that justifies part of an axis score.
 *
 * An agent never reports a bare number: every point of score is traceable to
 * an item naming the feature, what was measured, what it is compared with,
 * which way it moved and how much of the score it contributed.
 */
export interface EvidenceItem {
  baseline: FiniteFloat;
  contribution: Probability;
  direction: EvidenceDirection;
  evidence_refs?: EvidenceRefs3;
  feature: SignalName;
  note: HumanText;
  value: FiniteFloat;
}
/**
 * The fused, evidence-backed answer, with its differential diagnosis.
 *
 * ``verdict_class`` comes from the ordered rule table - crisp, operator-owned
 * and explainable. ``distribution`` is the same signatures read softly, so the
 * runner-up is visible rather than hidden. Every class that lost is recorded
 * in ``rejected_alternatives`` with the requirement it failed, so the answer
 * can be argued with rather than merely believed.
 */
export interface Verdict {
  assessment_ids?: AssessmentIds;
  confidence: Probability;
  corroborating_kinds?: CorroboratingKinds;
  distribution: Distribution;
  evidence?: Evidence1;
  reason: HumanText;
  reason_subtype?: ReasonSubtype | null;
  rejected_alternatives?: RejectedAlternatives;
  rule_id: Identifier;
  services?: Services1;
  ts: UtcDatetime;
  verdict_class: VerdictClass;
  verdict_id: Identifier;
}
export interface Distribution {
  [k: string]: Probability;
}
/**
 * One diagnosis that was considered and the evidence that ruled it out.
 */
export interface RejectedAlternative {
  reason: HumanText;
  verdict_class: VerdictClass;
}
/**
 * One real-world problem, assembled from the storm of symptoms it caused.
 *
 * A single fault lights many detectors across many services. An incident is
 * the collapse of that storm into the one thing an on-call person is actually
 * dealing with: co-occurring episodes on services that are near each other in
 * the topology become one incident, not twelve alerts.
 *
 * Identity is anchored to the earliest episode in the cluster, so the incident
 * keeps its id as the storm grows around it.
 */
export interface Incident {
  anchor_episode_id: Identifier;
  business_impact?: Probability | null;
  episode_ids: EpisodeIds;
  incident_id: Identifier;
  kinds: Kinds;
  last_activity_ts: UtcDatetime;
  merged_incident_ids?: MergedIncidentIds;
  note: HumanText;
  opened_ts: UtcDatetime;
  revision: Revision1;
  services: Services2;
  severity: IncidentSeverity;
  state: IncidentState;
}
