/**
 * Generated from platform/contracts/schema.json by npm run contracts:generate.
 * Edit the Python contracts, then run make contracts. Do not edit this file directly.
 */

/**
 * Public contracts exchanged between Sentinel planes.
 */
export type SentinelContract =
  | Observation
  | ContextWindow
  | DecompFrame
  | Symptom
  | SymptomEpisode
  | ChangeEvent
  | AgentAssessment
  | Verdict
  | Incident
  | Verification
  | Decision
  | ActionPlan
  | ActionOutcome
  | ActionControlRequest
  | ActionControlSnapshot
  | ActionControlResponse
  | AuditEntry
  | SnapshotInvalidation
  | ScoreProof
  | KpiResponse
  | IncidentFeedResponse
  | CausalGraphResponse
  | IncidentDetailResponse;
export type TelemetryScalar = string | boolean | number;
export type Identifier = string;
export type FlowRefs = Identifier[];
export type LogRefs = Identifier[];
export type SignalName = string;
export type TraceRefs = Identifier[];
export type UtcDatetime = string;
export type FiniteFloat = number;
export type Honesty = "REAL" | "SIMULATED";
export type HumanText = string;
export type Probability = number;
export type ContextIds = Identifier[];
export type EvidenceRefs = Identifier[];
/**
 * Deterministic evidence categories understood by the decision plane.
 */
export type SymptomKind =
  | "RESIDUAL_EXCEED"
  | "RATIO_DEFORM"
  | "LOG_BURST"
  | "EDGE_DEGRADED"
  | "SATURATION"
  | "DEPLOY_MARKER"
  | "DROP"
  | "SILENCE";
export type BreachTickCount = number;
export type EvidenceRefs1 = Identifier[];
export type Revision = number;
/**
 * Lifecycle state of an anti-flapping symptom episode.
 */
export type EpisodeStatus = "ACTIVE" | "CLOSED";
export type EvidenceRefs2 = Identifier[];
export type Honesty1 = "REAL" | "SIMULATED";
/**
 * How the system was changed by its operators, not by its callers.
 */
export type ChangeKind = "DEPLOY" | "ROLLOUT" | "FLAG" | "CONFIG";
/**
 * The independent axes a surge is judged on, one agent per axis.
 *
 * Each axis is scored from its own claimed evidence only. An attacker who
 * keeps one axis calm cannot thereby quiet another, because no agent ever
 * reads another agent's score.
 */
export type EvidenceAxis = "SECURITY" | "RELIABILITY" | "CHANGE_CONFIG" | "BUSINESS_IMPACT";
export type ContributingKinds = SymptomKind[];
export type CoveredKinds = SymptomKind[];
/**
 * Which way a measured value sits relative to its stated baseline.
 */
export type EvidenceDirection = "ABOVE_BASELINE" | "BELOW_BASELINE" | "AT_BASELINE";
export type EvidenceRefs3 = Identifier[];
export type Evidence = EvidenceItem[];
export type Services = Identifier[];
/**
 * Whether an agent had the coverage to score its axis at all.
 */
export type AgentStatus = "SCORED" | "INSUFFICIENT";
/**
 * Direction of an axis score against the agent's previous assessment.
 */
export type AgentTrend = "RISING" | "FALLING" | "STEADY" | "UNKNOWN";
export type AssessmentIds = Identifier[];
export type CorroboratingKinds = SymptomKind[];
export type Evidence1 = EvidenceItem[];
/**
 * A refinement that changes what a sane response looks like.
 *
 * ``CAPACITY_SHORTAGE`` exists so under-provisioning is answered with
 * "scale", never with "block": the traffic is real and the system is simply
 * too small for it.
 */
export type ReasonSubtype = "CAPACITY_SHORTAGE";
/**
 * What the fused evidence says is actually happening.
 */
export type VerdictClass = "EXPECTED_EVENT" | "ATTACK" | "OPERATIONAL_FAULT" | "CODE_CONFIG_FAULT" | "COMBINATION";
export type RejectedAlternatives = RejectedAlternative[];
export type Services1 = Identifier[];
/**
 * @minItems 1
 */
export type EpisodeIds = [Identifier, ...Identifier[]];
export type ImplicatedServices = Identifier[];
/**
 * @minItems 1
 */
export type Kinds = [SymptomKind, ...SymptomKind[]];
export type MergedIncidentIds = Identifier[];
export type Revision1 = number;
/**
 * @minItems 1
 */
export type Services2 = [Identifier, ...Identifier[]];
/**
 * How much this incident matters, in the language a responder pages on.
 */
export type IncidentSeverity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW";
/**
 * Where an incident is in its life, from first symptom to resolved.
 */
export type IncidentState = "OPEN" | "MITIGATING" | "MONITORING" | "RESOLVED";
/**
 * @minItems 1
 */
export type Checks = [VerificationCheck, ...VerificationCheck[]];
/**
 * How one deterministic check answered, including an honest vacuous pass.
 */
export type CheckOutcome = "PASSED" | "FAILED" | "BOOTSTRAP";
export type Confirmed = boolean;
/**
 * What the platform does about one incident, on a graded ladder.
 *
 * ``SUPPRESS`` is silence with a stated reason - nothing is happening, or an
 * operator has taken responsibility for the noise. ``ALERT`` tells a person
 * without paging them. ``ACT`` is autonomous, reversible remediation.
 * ``ESCALATE_TO_HUMAN`` hands the problem over untouched.
 * ``AUTO_CONTAIN_THEN_ESCALATE`` does both: contain the immediate harm, then
 * bring in a person, which is the only sane answer to a verified attack.
 */
export type DecisionAction = "SUPPRESS" | "ALERT" | "ACT" | "ESCALATE_TO_HUMAN" | "AUTO_CONTAIN_THEN_ESCALATE";
export type ApprovalReasons = HumanText[];
export type Confirmed1 = boolean;
export type EscalationReasons = HumanText[];
export type FloorsApplied = Identifier[];
export type GuardsApplied = Identifier[];
export type RequiresHumanApproval = boolean;
/**
 * Why an operator asked the platform to hold back.
 *
 * ``CHANGE_FREEZE`` forbids autonomous action without quieting anything: the
 * problem is still reported, we simply do not touch production during the
 * freeze. ``MAINTENANCE`` is the stronger claim that expected disruption on
 * named services is not worth reporting.
 */
export type SuppressionKind = "CHANGE_FREEZE" | "MAINTENANCE";
/**
 * The rungs of the remediation ladder, cheapest and safest first.
 *
 * The ordering of the rungs into ladders, and which rung a given diagnosis
 * earns, is operator-owned configuration - this enum is only the vocabulary
 * those ladders are written in.
 */
export type ActionKind =
  "OBSERVE" | "RATE_LIMIT" | "THROTTLE" | "SCALE" | "FLAG_FLIP" | "RESTART" | "ISOLATE" | "ROLLBACK";
/**
 * Which system an action is carried out against.
 *
 * ``SIMULATED`` is a first-class member rather than a test fixture: the
 * platform must be demonstrable end to end with no cluster attached, and an
 * adapter that touches nothing has to say so in the audit trail like any
 * other.
 */
export type ActuatorKind = "KUBERNETES" | "MESH" | "FEATURE_FLAG" | "SIMULATED";
export type Honesty2 = "REAL" | "SIMULATED";
export type ActionParameterValue = string | boolean | number;
export type RequiresHumanApproval1 = boolean;
export type Reversible = boolean;
export type Approvals = Identifier[];
export type Deduplicated = boolean;
export type DryRun = boolean;
export type GatesPassed = Identifier[];
export type Honesty3 = "REAL" | "SIMULATED";
export type Observed = HumanText[];
/**
 * How far one action got, and whether the world was touched.
 *
 * ``SIMULATED`` means nothing was touched - either the caller asked for a
 * simulation or the executor is in dry-run mode. ``APPLIED`` means the effect
 * was put in place; ``VERIFIED`` means it was afterwards observed to actually
 * be in place, which is a different and stronger claim. ``FAILED`` is the
 * honest answer when an actuator could not finish, and it deliberately does
 * not assert whether the world changed - only a ``verify`` can settle that.
 */
export type ActionStatus = "SIMULATED" | "APPLIED" | "VERIFIED" | "REVERTED" | "FAILED";
/**
 * The complete mutation vocabulary exposed to a client.
 */
export type ActionControlIntent = "APPROVE" | "REJECT" | "ROLLBACK";
export type PlanRevision = number;
export type Approvals1 = ActionApproval[];
/**
 * Whether one deterministic safety gate admitted the exact plan.
 */
export type ActionGateStatus = "PASSED" | "REFUSED";
export type GuardResults = ActionGateResult[];
export type PlanRevision1 = number;
export type CanaryShares = number[];
export type RequiredApprovalCount = number;
export type RequiresHumanApproval2 = boolean;
export type TtlSeconds = number;
/**
 * Durable progress of one immutable plan revision.
 */
export type ActionControlState =
  | "AWAITING_APPROVAL"
  | "APPLY_REQUESTED"
  | "REJECTED"
  | "APPLIED"
  | "VERIFIED"
  | "FAILED"
  | "ROLLBACK_REQUESTED"
  | "ROLLED_BACK"
  | "REFUSED"
  | "SIMULATED";
export type Status = string;
export type Honesty4 = "REAL" | "SIMULATED";
/**
 * What kind of thing the ledger is recording.
 *
 * Deliberately small. The ledger records what the platform *decided* and what
 * it *did about it*, which is the pair a person needs to reconstruct an
 * incident; telemetry lives in the stores that are built for it.
 */
export type AuditEventKind =
  | "DECISION"
  | "ACTION_PLANNED"
  | "ACTION_APPLIED"
  | "ACTION_VERIFIED"
  | "ACTION_REVERTED"
  | "ACTION_REFUSED"
  | "ROLLBACK"
  | "BREAKER_OPENED"
  | "APPROVAL";
export type Sequence = number;
/**
 * Named SSE events understood by the product surface.
 */
export type StreamEventKind = "snapshot.invalidate";
/**
 * @minItems 1
 */
export type Resources = [SnapshotResource, ...SnapshotResource[]];
/**
 * Authoritative snapshots an invalidation may ask the browser to refetch.
 */
export type SnapshotResource = "all" | "health" | "decomposition" | "incidents" | "actions" | "audit";
/**
 * @minItems 1
 */
export type CaptureIds = [Identifier, ...Identifier[]];
export type ConfigFingerprint = string;
export type GateStatus = "pass" | "fail";
/**
 * @minItems 1
 */
export type HeadlineMetrics = [ScoreHeadline, ...ScoreHeadline[]];
export type SampleCount = number;
/**
 * Whether a number was actually measured.
 */
export type KpiStatus = "ok" | "insufficient";
export type UnitName = string;
export type SeedPurpose = "held_out";
export type StimulusHonesty = "SIMULATED";
export type TelemetryHonesty = "REAL";
export type Version = 1;
/**
 * The four reliability questions on the command centre.
 */
export type KpiKey = "detection_latency" | "autonomous_mttr" | "quiet_day_false_acts" | "protected_cohort_integrity";
export type SampleCount1 = number;
export type Metrics = KpiMetric[];
export type Status1 = "ready" | "degraded";
export type Count = number;
/**
 * Whether the displayed confidence has a calibration basis.
 */
export type IncidentConfidenceStatus = "calibrated" | "insufficient";
/**
 * @maxItems 2
 */
export type Evidence2 = [] | [IncidentEvidenceValue] | [IncidentEvidenceValue, IncidentEvidenceValue];
export type Honesty5 = "REAL" | "SIMULATED";
export type Muted = boolean;
/**
 * @minItems 1
 */
export type Services3 = [Identifier, ...Identifier[]];
export type Incidents = IncidentFeedItem[];
export type Limit = number;
export type Status2 = "ready" | "degraded";
export type Active = boolean;
export type EvidenceEpisodeIds = Identifier[];
export type Edges = CausalGraphEdge[];
export type Honesty6 = "REAL" | "SIMULATED";
/**
 * @minItems 1
 */
export type Nodes = [CausalGraphNode, ...CausalGraphNode[]];
export type ActiveEpisodeCount = number;
export type Criticality = "low" | "medium" | "high" | "critical";
export type Implicated = boolean;
export type IsOrigin = boolean;
export type SymptomKinds = SymptomKind[];
export type Tier = "edge" | "application" | "data" | "infrastructure";
export type Status3 = "ready" | "empty" | "degraded";
export type Entries = AuditEntry[];
/**
 * @maxItems 500
 */
export type Frames = DecompFrame[];
export type Status4 = "available" | "insufficient";
export type Truncated = boolean;
export type Baseline = number;
export type EvidenceRefs4 = Identifier[];
export type Services4 = Identifier[];
export type SymptomKinds1 = SymptomKind[];
export type Value = number;
export type Evidence3 = IncidentEvidenceProof[];
export type Mode = "LIVE" | "REPLAY";
export type Seed = number | null;
export type Stimulus = "REAL" | "SIMULATED";
export type Telemetry = "REAL" | "SIMULATED";
export type RejectedAlternatives1 = RejectedAlternative[];
/**
 * @minItems 1
 */
export type Services5 = [Identifier, ...Identifier[]];
export type Distribution1 = VerdictProbability[];
export type Status5 = "decided" | "insufficient";
export type Status6 = "ready" | "not_found" | "degraded";

/**
 * One event-time telemetry value, containing evidence but never answer-key data.
 */
export interface Observation {
  attributes?: Attributes;
  flow_refs?: FlowRefs;
  log_refs?: LogRefs;
  observation_id: Identifier;
  service: Identifier;
  signal: SignalName;
  trace_refs?: TraceRefs;
  ts: UtcDatetime;
  unit?: string;
  value: FiniteFloat;
}
export interface Attributes {
  [k: string]: TelemetryScalar;
}
/**
 * A trusted external event and the signals whose volume it may explain.
 */
export interface ContextWindow {
  context_id: Identifier;
  event_type: Identifier;
  expected_delta: ExpectedDelta;
  honesty: Honesty;
  name: HumanText;
  source: Identifier;
  trust_score: Probability;
  valid_from: UtcDatetime;
  valid_to: UtcDatetime;
}
export interface ExpectedDelta {
  [k: string]: FiniteFloat;
}
/**
 * Full-resolution split of observed telemetry into explained and residual parts.
 */
export interface DecompFrame {
  band_high: FiniteFloat;
  band_low: FiniteFloat;
  context_ids?: ContextIds;
  explained_base: FiniteFloat;
  explained_event: FiniteFloat;
  frame_id: Identifier;
  observation_id: Identifier;
  observed: FiniteFloat;
  residual: FiniteFloat;
  residual_score: Probability;
  service: Identifier;
  signal: SignalName;
  ts: UtcDatetime;
}
/**
 * One scored, human-legible piece of evidence about abnormal behavior.
 */
export interface Symptom {
  evidence_refs?: EvidenceRefs;
  kind: SymptomKind;
  note: HumanText;
  onset_ts: UtcDatetime;
  score: Probability;
  service: Identifier;
  signal: SignalName;
  symptom_id: Identifier;
}
/**
 * A hysteresis-guarded lifecycle over repeated symptoms of one key.
 *
 * An episode groups the recurring symptoms of a single ``(kind, service,
 * signal)`` into one durable incident-precursor. It opens only after a symptom
 * persists (breach persistence + a score deadband) and closes only after it
 * clears for long enough, so a momentary blip can never open one and a key can
 * never flap. Raw ``Symptom`` evidence is untouched; an episode only points at
 * it via the opening, peak and latest symptom ids.
 */
export interface SymptomEpisode {
  breach_tick_count: BreachTickCount;
  closed_ts?: UtcDatetime | null;
  confirmed_ts: UtcDatetime;
  episode_id: Identifier;
  evidence_refs?: EvidenceRefs1;
  kind: SymptomKind;
  last_breach_ts: UtcDatetime;
  latest_symptom_id: Identifier;
  opened_ts: UtcDatetime;
  opening_symptom_id: Identifier;
  peak_score: Probability;
  peak_symptom_id: Identifier;
  revision: Revision;
  service: Identifier;
  signal: SignalName;
  status: EpisodeStatus;
}
/**
 * One recorded operator change, the raw material of deploy-correlated pressure.
 *
 * A change is a fact about the system's own history, never a conclusion about
 * an incident. It carries its own honesty label because the MVP feed mixes an
 * operator-maintained ledger with changes observed from the cluster.
 */
export interface ChangeEvent {
  change_id: Identifier;
  evidence_refs?: EvidenceRefs2;
  honesty: Honesty1;
  kind: ChangeKind;
  revision?: Identifier | null;
  service: Identifier;
  source: Identifier;
  summary: HumanText;
  ts: UtcDatetime;
}
/**
 * One agent's evidence-backed verdict about one axis at one event time.
 *
 * A calm axis (``SCORED`` at ``0.0`` with no evidence) is a genuine finding:
 * the claimed detectors ran and saw nothing. An axis whose detectors produced
 * no coverage is ``INSUFFICIENT`` instead, so absence of evidence is never
 * silently reported as evidence of absence.
 */
export interface AgentAssessment {
  assessment_id: Identifier;
  axis: EvidenceAxis;
  contributing_kinds?: ContributingKinds;
  covered_kinds?: CoveredKinds;
  evidence?: Evidence;
  note: HumanText;
  score: Probability;
  services?: Services;
  status: AgentStatus;
  trend: AgentTrend;
  ts: UtcDatetime;
}
/**
 * One measured value that justifies part of an axis score.
 *
 * An agent never reports a bare number: every point of score is traceable to
 * an item naming the feature, what was measured, what it is compared with,
 * which way it moved and how much of the score it contributed.
 */
export interface EvidenceItem {
  baseline: FiniteFloat;
  contribution: Probability;
  direction: EvidenceDirection;
  evidence_refs?: EvidenceRefs3;
  feature: SignalName;
  note: HumanText;
  value: FiniteFloat;
}
/**
 * The fused, evidence-backed answer, with its differential diagnosis.
 *
 * ``verdict_class`` comes from the ordered rule table - crisp, operator-owned
 * and explainable. ``distribution`` is the same signatures read softly, so the
 * runner-up is visible rather than hidden. Every class that lost is recorded
 * in ``rejected_alternatives`` with the requirement it failed, so the answer
 * can be argued with rather than merely believed.
 */
export interface Verdict {
  assessment_ids?: AssessmentIds;
  confidence: Probability;
  corroborating_kinds?: CorroboratingKinds;
  distribution: Distribution;
  evidence?: Evidence1;
  reason: HumanText;
  reason_subtype?: ReasonSubtype | null;
  rejected_alternatives?: RejectedAlternatives;
  rule_id: Identifier;
  services?: Services1;
  ts: UtcDatetime;
  verdict_class: VerdictClass;
  verdict_id: Identifier;
}
export interface Distribution {
  [k: string]: Probability;
}
/**
 * One diagnosis that was considered and the evidence that ruled it out.
 */
export interface RejectedAlternative {
  reason: HumanText;
  verdict_class: VerdictClass;
}
/**
 * One real-world problem, assembled from the storm of symptoms it caused.
 *
 * A single fault lights many detectors across many services. An incident is
 * the collapse of that storm into the one thing an on-call person is actually
 * dealing with: co-occurring episodes on services that are near each other in
 * the topology become one incident, not twelve alerts.
 *
 * Identity is anchored to the earliest episode in the cluster, so the incident
 * keeps its id as the storm grows around it.
 *
 * ``services`` are the services that carried a symptom. ``implicated_services``
 * are the ones named only by the evidence - a service whose caller's degraded
 * dependency edge accuses it while it emits nothing of its own. The two are
 * kept apart because they are different claims: one was observed misbehaving,
 * the other was merely blamed, and a real cascade's origin is routinely the
 * second kind.
 */
export interface Incident {
  anchor_episode_id: Identifier;
  business_impact?: Probability | null;
  episode_ids: EpisodeIds;
  implicated_services?: ImplicatedServices;
  incident_id: Identifier;
  kinds: Kinds;
  last_activity_ts: UtcDatetime;
  merged_incident_ids?: MergedIncidentIds;
  note: HumanText;
  opened_ts: UtcDatetime;
  origin_confidence?: Probability | null;
  origin_service?: Identifier | null;
  revision: Revision1;
  services: Services2;
  severity: IncidentSeverity;
  state: IncidentState;
}
/**
 * The four deterministic checks a hypothesis must survive before it is acted on.
 *
 * Nothing here proposes anything. Each check is arithmetic over telemetry and
 * committed topology, and all four must hold: a hypothesis that is merely
 * plausible is left unconfirmed, which downstream means pending review rather
 * than action.
 *
 * ``BOOTSTRAP`` is a vacuous pass, recorded as such and never as a
 * confirmation. It exists only so that an empty incident memory cannot make
 * confirmation impossible forever.
 */
export interface Verification {
  checks: Checks;
  confirmed: Confirmed;
  incident_id: Identifier;
  ts: UtcDatetime;
  verification_id: Identifier;
}
/**
 * One non-LLM check and the evidence-derived reason for its answer.
 */
export interface VerificationCheck {
  detail: HumanText;
  name: Identifier;
  outcome: CheckOutcome;
}
/**
 * What the platform decided to do about one incident, and what it may not do.
 *
 * The decision is taken on the incident's strongest evidence rather than on
 * whatever the latest tick happened to read - a storm that has gone quiet for
 * a moment is still the storm - and ``evidence_ts`` records the tick that
 * evidence was measured at, so a decision never quietly presents old evidence
 * as current.
 *
 * Three safety properties are enforced here rather than left to the gate,
 * because the contract is the last thing between a hypothesis and production:
 * an acting decision must be confirmed, must carry a verdict, and must name a
 * ``target_service`` that was computed from evidence. ``requires_human_approval``
 * is derived from ``approval_reasons`` so a decision can never claim to be
 * approved-free while listing the reasons it is not.
 *
 * **``approval_reasons`` and ``escalation_reasons`` are different facts and are
 * deliberately separate fields.** ``approval_reasons`` is *why a person must
 * sign before this happens*; ``escalation_reasons`` is *why a person is being
 * brought in*. They were one field until 2026-07-25, and the consequence was
 * found by running the remediation loop over a recorded capture: every
 * ``AUTO_CONTAIN_THEN_ESCALATE`` decision - the platform's designed answer to a
 * verified attack, whose whole point is to contain the harm *and then* fetch
 * somebody - was refused by the executor for want of a signature, because
 * "a person is being told" had been recorded in the field the action plane
 * reads as "a person must consent". 98 out of 98 on `combo_night`. Containing
 * an attack and asking permission to contain it are not the same decision, and
 * a system that cannot say which one it means will always pick the wrong one.
 */
export interface Decision {
  action: DecisionAction;
  approval_reasons?: ApprovalReasons;
  confidence?: Probability | null;
  confirmed: Confirmed1;
  decision_id: Identifier;
  escalation_reasons?: EscalationReasons;
  evidence_ts: UtcDatetime;
  floors_applied?: FloorsApplied;
  guards_applied?: GuardsApplied;
  incident_id: Identifier;
  reason: HumanText;
  requires_human_approval: RequiresHumanApproval;
  rule_id: Identifier;
  severity: IncidentSeverity;
  suppression?: AppliedSuppression | null;
  target_service?: Identifier | null;
  ts: UtcDatetime;
  verdict_class?: VerdictClass | null;
  verdict_id?: Identifier | null;
  verification_id: Identifier;
}
/**
 * The operator-owned window that held a decision back, and who owns it.
 *
 * A window that could not name an owner, a reason and an expiry would be an
 * anonymous, permanent silence. All three are required, so every suppressed
 * decision records the person who took responsibility for it and the moment
 * that responsibility runs out.
 */
export interface AppliedSuppression {
  expires_ts: UtcDatetime;
  kind: SuppressionKind;
  owner: Identifier;
  reason: HumanText;
  window_id: Identifier;
}
/**
 * One concrete, reversible effect an actuator proposes to put in place.
 *
 * A plan is built from a decision that already decided to act, and it carries
 * the safety-critical facts forward unchanged: the target service is the
 * origin the causal collapse computed from evidence, and the approval
 * requirement is the policy gate's, never the adapter's opinion.
 *
 * ``expected_effect`` is required because an action nobody can check is not
 * something this platform takes: it states, in advance, what ``verify`` should
 * find once the effect is in place.
 */
export interface ActionPlan {
  action_kind: ActionKind;
  actuator: ActuatorKind;
  decision_id: Identifier;
  estimated_blast_fraction: Probability;
  expected_effect: HumanText;
  honesty: Honesty2;
  idempotency_key: Identifier;
  incident_id: Identifier;
  parameters?: Parameters;
  plan_id: Identifier;
  reason: HumanText;
  requires_human_approval: RequiresHumanApproval1;
  reversible: Reversible;
  target_ref: Identifier;
  target_service: Identifier;
  ts: UtcDatetime;
}
export interface Parameters {
  [k: string]: ActionParameterValue;
}
/**
 * What one actuator call actually did, recorded whether it worked or not.
 *
 * ``dry_run`` and ``SIMULATED`` are the same fact stated twice, and the
 * contract keeps them in agreement: this is the single place that makes "we
 * were only pretending" impossible to confuse with "we changed production".
 *
 * ``deduplicated`` marks an outcome that was returned *without* calling the
 * actuator, because the effect this key names was already in place. It is not
 * a failure and not a no-op error - it is the idempotency key doing its job.
 */
export interface ActionOutcome {
  approvals?: Approvals;
  deduplicated?: Deduplicated;
  detail: HumanText;
  dry_run: DryRun;
  gates_passed?: GatesPassed;
  honesty: Honesty3;
  idempotency_key: Identifier;
  observed?: Observed;
  outcome_id: Identifier;
  plan_id: Identifier;
  revert_token?: Identifier | null;
  status: ActionStatus;
  ts: UtcDatetime;
}
/**
 * An operator's intent against one stable, server-held plan revision.
 */
export interface ActionControlRequest {
  incident_id: Identifier;
  intent: ActionControlIntent;
  plan_revision: PlanRevision;
}
/**
 * Authoritative durable control state returned after every mutation.
 */
export interface ActionControlSnapshot {
  approvals?: Approvals1;
  created_at: UtcDatetime;
  guard_results: GuardResults;
  incident_id: Identifier;
  latest_outcome: ActionOutcome | null;
  plan: ActionPlan;
  plan_revision: PlanRevision1;
  rejected_at?: UtcDatetime | null;
  rejected_by?: Identifier | null;
  rung: ActionRungSnapshot;
  state: ActionControlState;
  updated_at: UtcDatetime;
}
/**
 * One server-authenticated identity approving one plan revision once.
 */
export interface ActionApproval {
  actor: Identifier;
  approved_at: UtcDatetime;
}
/**
 * One measured deterministic guard result for the exact plan.
 */
export interface ActionGateResult {
  detail: HumanText;
  gate_id: Identifier;
  status: ActionGateStatus;
}
/**
 * The exact committed ladder choice from which the plan was built.
 */
export interface ActionRungSnapshot {
  action_kind: ActionKind;
  actuator: ActuatorKind;
  canary_parameter?: Identifier | null;
  canary_shares?: CanaryShares;
  ladder_id: Identifier;
  maximum_blast_fraction: Probability;
  parameters?: Parameters1;
  reason: HumanText;
  required_approval_count: RequiredApprovalCount;
  requires_human_approval: RequiresHumanApproval2;
  rung_id: Identifier;
  ttl_seconds: TtlSeconds;
}
export interface Parameters1 {
  [k: string]: ActionParameterValue;
}
/**
 * Typed API response for the latest authoritative plan revision.
 */
export interface ActionControlResponse {
  control: ActionControlSnapshot;
  status: Status;
}
/**
 * One immutable record, bound to the entry before it by its own hash.
 */
export interface AuditEntry {
  actor: Identifier;
  body?: Body;
  decision_id?: Identifier | null;
  entry_hash: Identifier;
  entry_id: Identifier;
  honesty: Honesty4;
  incident_id?: Identifier | null;
  kind: AuditEventKind;
  plan_id?: Identifier | null;
  previous_hash: Identifier;
  sequence: Sequence;
  summary: HumanText;
  ts: UtcDatetime;
}
export interface Body {
  [k: string]: unknown;
}
/**
 * One typed signal that one or more REST snapshots are stale.
 */
export interface SnapshotInvalidation {
  event_id: Identifier;
  kind?: StreamEventKind;
  resources: Resources;
  ts: UtcDatetime;
}
/**
 * Immutable output of one held-out scoring invocation.
 */
export interface ScoreProof {
  capture_ids: CaptureIds;
  config_fingerprint: ConfigFingerprint;
  evidence_end: UtcDatetime;
  evidence_start: UtcDatetime;
  gate_status: GateStatus;
  headline_metrics: HeadlineMetrics;
  proof_id: Identifier;
  report_path: Identifier;
  seed_purpose: SeedPurpose;
  stimulus_honesty: StimulusHonesty;
  telemetry_honesty: TelemetryHonesty;
  version: Version;
}
/**
 * One compact metric from a score-proof artifact.
 */
export interface ScoreHeadline {
  key: Identifier;
  label: HumanText;
  sample_count: SampleCount;
  status: KpiStatus;
  unit: UnitName;
  value: FiniteFloat | null;
}
/**
 * The command centre's one typed reliability snapshot.
 */
export interface KpiResponse {
  detail?: HumanText | null;
  latest_score_proof: ScoreProof | null;
  metrics: Metrics;
  status: Status1;
}
/**
 * One reliability KPI with enough provenance to interpret it.
 */
export interface KpiMetric {
  definition: HumanText;
  key: KpiKey;
  label: HumanText;
  provenance: HumanText;
  sample_count: SampleCount1;
  status: KpiStatus;
  unit: UnitName;
  value: FiniteFloat | null;
  window: KpiWindow;
}
/**
 * The evidence interval behind a KPI, or why no interval exists.
 */
export interface KpiWindow {
  description: HumanText;
  end: UtcDatetime | null;
  start: UtcDatetime | null;
}
/**
 * One bounded latest-first REST snapshot.
 */
export interface IncidentFeedResponse {
  count: Count;
  detail?: HumanText | null;
  incidents: Incidents;
  limit: Limit;
  status: Status2;
}
/**
 * One evidence-first card in the authoritative incident snapshot.
 */
export interface IncidentFeedItem {
  action: IncidentActionState;
  confidence: IncidentConfidence;
  evidence: Evidence2;
  explanation: HumanText | null;
  honesty: Honesty5;
  incident_id: Identifier;
  muted: Muted;
  opened_at: UtcDatetime;
  origin_service: Identifier | null;
  reason: HumanText;
  services: Services3;
  severity: IncidentSeverity;
  state: IncidentState;
  updated_at: UtcDatetime;
  verdict_class: VerdictClass | null;
}
/**
 * What was decided, separately from what an actuator proved it did.
 */
export interface IncidentActionState {
  decision_action: DecisionAction;
  detail: HumanText;
  effect_status: ActionStatus | null;
}
/**
 * A calibrated confidence or an explicit refusal to display one.
 */
export interface IncidentConfidence {
  note: HumanText;
  status: IncidentConfidenceStatus;
  value: Probability | null;
}
/**
 * One measured value compact enough for an incident card.
 */
export interface IncidentEvidenceValue {
  baseline: FiniteFloat;
  direction: EvidenceDirection;
  feature: SignalName;
  note: HumanText;
  value: FiniteFloat;
}
/**
 * The authoritative current-incident graph or an explicit absence.
 */
export interface CausalGraphResponse {
  detail: HumanText | null;
  graph: CausalGraph | null;
  status: Status3;
}
/**
 * One durable graph revision for an incident.
 *
 * Resolved revisions remain valid durable state so closing an incident can
 * advance both records atomically. The repository's current-graph query
 * filters them out.
 */
export interface CausalGraph {
  edges: Edges;
  honesty: Honesty6;
  incident_id: Identifier;
  incident_state: IncidentState;
  nodes: Nodes;
  origin_confidence: Probability | null;
  origin_service: Identifier | null;
  updated_at: UtcDatetime;
}
/**
 * One topology edge rendered in possible propagation direction.
 *
 * Configuration says ``caller depends on dependency``. This public edge is
 * deliberately reversed to ``dependency -> caller`` so its arrow answers the
 * incident-response question: where could an observed effect propagate?
 */
export interface CausalGraphEdge {
  active: Active;
  evidence_episode_ids: EvidenceEpisodeIds;
  note: HumanText;
  source_service: Identifier;
  target_service: Identifier;
}
/**
 * One committed topology service with evidence-derived incident heat.
 */
export interface CausalGraphNode {
  active_episode_count: ActiveEpisodeCount;
  criticality: Criticality;
  implicated: Implicated;
  is_origin: IsOrigin;
  note: HumanText;
  origin_confidence: Probability | null;
  service: Identifier;
  symptom_heat: Probability;
  symptom_kinds: SymptomKinds;
  tier: Tier;
}
/**
 * Ready/not-found/degraded response for one stable incident id.
 */
export interface IncidentDetailResponse {
  detail: IncidentDetail | null;
  message: HumanText | null;
  status: Status6;
}
/**
 * One evidence-complete incident revision for the proof screen.
 */
export interface IncidentDetail {
  action_log: IncidentActionLog;
  causal_graph: CausalGraph;
  decomposition: IncidentDecomposition;
  evidence: Evidence3;
  incident_id: Identifier;
  opened_at: UtcDatetime;
  origin_confidence: Probability | null;
  origin_service: Identifier | null;
  provenance: IncidentProvenance;
  reason: HumanText;
  rejected_alternatives: RejectedAlternatives1;
  services: Services5;
  severity: IncidentSeverity;
  state: IncidentState;
  updated_at: UtcDatetime;
  verdict: IncidentVerdictProof;
  verification: Verification;
}
/**
 * The decision plus every attached immutable action/audit record.
 */
export interface IncidentActionLog {
  decision: Decision;
  detail: HumanText;
  entries: Entries;
}
/**
 * The primary full-resolution incident series, or explicit insufficiency.
 */
export interface IncidentDecomposition {
  detail: HumanText;
  end: UtcDatetime;
  frames: Frames;
  service: Identifier | null;
  signal: SignalName | null;
  start: UtcDatetime;
  status: Status4;
  truncated: Truncated;
}
/**
 * One typed, independently scored evidence item behind the verdict.
 */
export interface IncidentEvidenceProof {
  assessment_id: Identifier;
  axis: EvidenceAxis;
  baseline: Baseline;
  contribution: Probability;
  direction: EvidenceDirection;
  evidence_refs: EvidenceRefs4;
  feature: SignalName;
  note: HumanText;
  services: Services4;
  symptom_kinds: SymptomKinds1;
  value: Value;
}
/**
 * What was measured and how the stimulus reached the platform.
 */
export interface IncidentProvenance {
  capture_id?: Identifier | null;
  mode: Mode;
  seed?: Seed;
  stimulus: Stimulus;
  telemetry: Telemetry;
}
/**
 * The winning class and complete support distribution, with honest calibration.
 */
export interface IncidentVerdictProof {
  calibration: IncidentConfidence;
  distribution: Distribution1;
  reason_subtype: ReasonSubtype | null;
  status: Status5;
  verdict_class: VerdictClass | null;
}
/**
 * One member of the complete deterministic verdict distribution.
 */
export interface VerdictProbability {
  probability: Probability;
  verdict_class: VerdictClass;
}
