apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: sentinel-metrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: sentinel-logs
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Tempo
    uid: sentinel-traces
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToLogsV2:
        datasourceUid: sentinel-logs
      tracesToMetrics:
        datasourceUid: sentinel-metrics
