import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compileFromFile } from "json-schema-to-typescript";

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = resolve(webRoot, "../platform/contracts/schema.json");
const typesPath = resolve(webRoot, "src/contracts/types.ts");
const bannerComment = `/**
 * Generated from platform/contracts/schema.json by npm run contracts:generate.
 * Edit the Python contracts, then run make contracts. Do not edit this file directly.
 */`;

async function renderTypes() {
  return compileFromFile(schemaPath, {
    additionalProperties: false,
    bannerComment,
    enableConstEnums: false,
    unknownAny: true,
  });
}

async function generate() {
  await mkdir(dirname(typesPath), { recursive: true });
  await writeFile(typesPath, await renderTypes(), "utf8");
}

async function check() {
  const expected = await renderTypes();
  let actual;
  try {
    actual = await readFile(typesPath, "utf8");
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      actual = "";
    } else {
      throw error;
    }
  }

  if (actual !== expected) {
    process.stderr.write("generated contract types are stale: run make contracts\n");
    process.exitCode = 1;
  }
}

const command = process.argv[2];
if (command === "generate") {
  await generate();
} else if (command === "check") {
  await check();
} else {
  process.stderr.write("usage: node scripts/contracts.mjs <generate|check>\n");
  process.exitCode = 2;
}
