export const ACTION_RESPONSE = {
  status: 'ready',
  control: {
    incident_id: 'incident-proof-1',
    plan_revision: 1,
    state: 'AWAITING_APPROVAL',
    rung: {
      rung_id: 'rate-limit-invalid-credentials',
      ladder_id: 'attack',
      actuator: 'MESH',
      action_kind: 'RATE_LIMIT',
      parameters: { cohort: 'invalid-credentials', requests_per_second: 5 },
      ttl_seconds: 300,
      requires_human_approval: true,
      required_approval_count: 1,
      maximum_blast_fraction: 0.2,
      reason: 'The verified hostile residual earned this committed rung.',
      canary_parameter: null,
      canary_shares: [],
    },
    plan: {
      plan_id: 'plan-proof-1',
      ts: '2026-07-28T12:00:00Z',
      decision_id: 'decision-proof-1',
      incident_id: 'incident-proof-1',
      actuator: 'MESH',
      action_kind: 'RATE_LIMIT',
      target_service: 'frontend',
      target_ref: 'route/login',
      parameters: { cohort: 'invalid-credentials', requests_per_second: 5 },
      reason: 'The verified hostile residual earned this committed rung.',
      expected_effect: 'Invalid-credential traffic remains under five requests per second.',
      reversible: true,
      requires_human_approval: true,
      estimated_blast_fraction: 0.1,
      idempotency_key: 'd'.repeat(64),
      honesty: 'REAL',
    },
    guard_results: [
      {
        gate_id: 'protected-cohort-unharmed',
        status: 'PASSED',
        detail: 'The committed cohort allowance was respected.',
      },
      {
        gate_id: 'blast-radius-within-the-rung-ceiling',
        status: 'PASSED',
        detail: 'The measured blast radius stayed inside the rung ceiling.',
      },
    ],
    latest_outcome: null,
    approvals: [],
    rejected_by: null,
    rejected_at: null,
    created_at: '2026-07-28T12:00:00Z',
    updated_at: '2026-07-28T12:00:00Z',
  },
  message: null,
};
